export const FIND_PRODUCT_BY_ID_REQUEST = 'FIND_PRODUCT_BY_ID_REQUEST'
export const FIND_PRODUCT_BY_ID_SUCCESS = 'FIND_PRODUCT_BY_ID_SUCCESS'
export const FIND_PRODUCT_BY_ID_FAILURE = 'FIND_PRODUCT_BY_ID_FAILURE'

export const DELETE_PRODUCT_BY_ID_REQUEST = 'DELETE_PRODUCT_BY_ID_REQUEST'
export const DELETE_PRODUCT_BY_ID_SUCCESS = 'DELETE_PRODUCT_BY_ID_SUCCESS'
export const DELETE_PRODUCT_BY_ID_FAILURE = 'DELETE_PRODUCT_BY_ID_FAILURE'

export const FIND_PRODUCTS_REQUEST = 'FIND_PRODUCTS_REQUEST'
export const FIND_PRODUCTS_SUCCESS = 'FIND_PRODUCTS_SUCCESS'
export const FIND_PRODUCTS_FAILURE = 'FIND_PRODUCTS_FAILURE'

export const FIND_PRODUCTS_BY_NAME_REQUEST = 'FIND_PRODUCTS_BY_NAME_REQUEST'
export const FIND_PRODUCTS_BY_NAME_SUCCESS = 'FIND_PRODUCTS_BY_NAME_SUCCESS'
export const FIND_PRODUCTS_BY_NAME_FAILURE = 'FIND_PRODUCTS_BY_NAME_FAILURE'    

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE'

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const INCREMENT_PRODUCT_VIEW_REQUEST = 'INCREMENT_PRODUCT_VIEW_REQUEST'
export const INCREMENT_PRODUCT_VIEW_SUCCESS = 'INCREMENT_PRODUCT_VIEW_SUCCESS'
export const INCREMENT_PRODUCT_VIEW_FAILURE = 'INCREMENT_PRODUCT_VIEW_FAILURE'

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS'

