export const GET_THIRD_LEVEL_CATEGORY = "GET_THIRD_LEVEL_CATEGORY";
export const GET_THIRD_LEVEL_CATEGORY_SUCCESS = "GET_THIRD_LEVEL_CATEGORY_SUCCESS";
export const GET_THIRD_LEVEL_CATEGORY_FAILED = "GET_THIRD_LEVEL_CATEGORY_FAILED";