export const GET_THIRD_LEVEL_CATEGORY = "GET_THIRD_LEVEL_CATEGORY";
export const GET_THIRD_LEVEL_CATEGORY_SUCCESS = "GET_THIRD_LEVEL_CATEGORY_SUCCESS";
export const GET_THIRD_LEVEL_CATEGORY_FAILED = "GET_THIRD_LEVEL_CATEGORY_FAILED";

export const GET_MEN_CATEGORIES = "GET_MEN_CATEGORIES";
export const GET_MEN_CATEGORIES_SUCCESS = "GET_MEN_CATEGORIES_SUCCESS";
export const GET_MEN_CATEGORIES_FAILED = "GET_MEN_CATEGORIES_FAILED";

export const GET_WOMEN_CATEGORIES = "GET_WOMEN_CATEGORIES";
export const GET_WOMEN_CATEGORIES_SUCCESS = "GET_WOMEN_CATEGORIES_SUCCESS";
export const GET_WOMEN_CATEGORIES_FAILED = "GET_WOMEN_CATEGORIES_FAILED";

export const GET_TOP_LEVEL_CATEGORY = "GET_TOP_LEVEL_CATEGORY";
export const GET_TOP_LEVEL_CATEGORY_SUCCESS = "GET_TOP_LEVEL_CATEGORY_SUCCESS";
export const GET_TOP_LEVEL_CATEGORY_FAILED = "GET_TOP_LEVEL_CATEGORY_FAILED";

export const GET_SECOND_LEVEL_CATEGORY = "GET_SECOND_LEVEL_CATEGORY";
export const GET_SECOND_LEVEL_CATEGORY_SUCCESS = "GET_SECOND_LEVEL_CATEGORY_SUCCESS";
export const GET_SECOND_LEVEL_CATEGORY_FAILED = "GET_SECOND_LEVEL_CATEGORY_FAILED";