export const GET_PROMOTIONS_REQUEST = "GET_PROMOTIONS_REQUEST";
export const GET_PROMOTIONS_SUCCESS = "GET_PROMOTIONS_SUCCESS";
export const GET_PROMOTIONS_FAILURE = "GET_PROMOTIONS_FAILURE";

export const REMOVE_PROMOTION_REQUEST = "REMOVE_PROMOTION_REQUEST";
export const REMOVE_PROMOTION_SUCCESS = "REMOVE_PROMOTION_SUCCESS";
export const REMOVE_PROMOTION_FAILURE = "REMOVE_PROMOTION_FAILURE";

export const APPLY_PROMOTION_REQUEST = "APPLY_PROMOTION_REQUEST";
export const APPLY_PROMOTION_SUCCESS = "APPLY_PROMOTION_SUCCESS";
export const APPLY_PROMOTION_FAILURE = "APPLY_PROMOTION_FAILURE";

export const CREATE_PROMOTION_REQUEST = "CREATE_PROMOTION_REQUEST";
export const CREATE_PROMOTION_SUCCESS = "CREATE_PROMOTION_SUCCESS";
export const CREATE_PROMOTION_FAILURE = "CREATE_PROMOTION_FAILURE";

export const UPDATE_PROMOTION_REQUEST = "UPDATE_PROMOTION_REQUEST";
export const UPDATE_PROMOTION_SUCCESS = "UPDATE_PROMOTION_SUCCESS";
export const UPDATE_PROMOTION_FAILURE = "UPDATE_PROMOTION_FAILURE";

export const DELETE_PROMOTION_REQUEST = "DELETE_PROMOTION_REQUEST";
export const DELETE_PROMOTION_SUCCESS = "DELETE_PROMOTION_SUCCESS";
export const DELETE_PROMOTION_FAILURE = "DELETE_PROMOTION_FAILURE";

export const TOGGLE_VISIBILITY_REQUEST = "TOGGLE_VISIBILITY_REQUEST";
export const TOGGLE_VISIBILITY_SUCCESS = "TOGGLE_VISIBILITY_SUCCESS";
export const TOGGLE_VISIBILITY_FAILURE = "TOGGLE_VISIBILITY_FAILURE";

export const FIND_PROMOTION_REQUEST = 'FIND_PROMOTION_REQUEST';
export const FIND_PROMOTION_SUCCESS = 'FIND_PROMOTION_SUCCESS';
export const FIND_PROMOTION_FAILURE = 'FIND_PROMOTION_FAILURE';
