export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE";

export const GET_REVIEWS_REQUEST = "GET_REVIEWS_REQUEST";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";
export const GET_REVIEWS_FAILURE = "GET_REVIEWS_FAILURE";

export const GET_ALL_REVIEWS_ADMIN_REQUEST = "GET_ALL_REVIEWS_ADMIN_REQUEST";
export const GET_ALL_REVIEWS_ADMIN_SUCCESS = "GET_ALL_REVIEWS_ADMIN_SUCCESS";
export const GET_ALL_REVIEWS_ADMIN_FAILURE = "GET_ALL_REVIEWS_ADMIN_FAILURE";

export const ADD_RESPONSE_REQUEST = "ADD_RESPONSE_REQUEST";
export const ADD_RESPONSE_SUCCESS = "ADD_RESPONSE_SUCCESS";
export const ADD_RESPONSE_FAILURE = "ADD_RESPONSE_FAILURE";

export const UPDATE_REPLY_REQUEST = "UPDATE_REPLY_REQUEST";
export const UPDATE_REPLY_SUCCESS = "UPDATE_REPLY_SUCCESS";
export const UPDATE_REPLY_FAILURE = "UPDATE_REPLY_FAILURE";

export const DELETE_REPLY_REQUEST = "DELETE_REPLY_REQUEST";
export const DELETE_REPLY_SUCCESS = "DELETE_REPLY_SUCCESS";
export const DELETE_REPLY_FAILURE = "DELETE_REPLY_FAILURE";

export const FIND_REVIEW_BY_PRODUCT = "FIND_REVIEW_BY_PRODUCT";
export const FIND_REVIEW_BY_PRODUCT_SUCCESS = "FIND_REVIEW_BY_PRODUCT_SUCCESS";
export const FIND_REVIEW_BY_PRODUCT_FAILED = "FIND_REVIEW_BY_PRODUCT_FAILED";

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';
