export const GET_ALL_USER_REQUESET = 'GET_ALL_USER_REQUEST'
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_FAILURE = 'GET_ALL_USER_FAILURE'

export const REMOVE_USER_REQUESET = 'REMOVE_USER_REQUEST'
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS'
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE'

export const FIND_USER_REQUEST = 'FIND_USER_REQUEST'
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS'
export const FIND_USER_FAILURE = 'FIND_USER_FAILURE'    

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'
